apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: shakulmittal/private:v2
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: secret-0
      - name: secret-3
      - name: secret-4
